name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasksdb
      DB_PORT: 5432
      DB_HOST: localhost
      PORT: 8080

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tasksdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Static analysis (go vet)
        run: go vet ./...

      - name: Lint check (golint)
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:latest
