name: Backend CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20


      - name: Install dependencies
        run: go mod tidy
        working-directory: ./backend

      - name: Run tests
        run: go test ./...
        working-directory: ./backend
