name: Full Project CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tasksdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasksdb
      DB_PORT: 5432
      DB_HOST: localhost
      PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # === BACKEND ===
      - name: Install Go dependencies
        run: |
          cd backend
          go mod tidy

      - name: Static analysis (go vet + golint)
        run: |
          cd backend
          go vet ./...
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Run backend tests
        run: |
          cd backend
          go test ./...

      # === FRONTEND ===
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # === DOCKER ===
      - name: Docker login
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }} ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextgo-frontend:${{ github.sha }} ./frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/nextgo-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nextgo-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextgo-frontend:latest
